unstable_features = true

brace_style = "PreferSameLine"
comment_width = 120
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 120
merge_derives = false
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
